server {
    server_name travelandrepeat.com.mx;

    # PROXY AL BACKEND DOCKER
    location /api/ {
        proxy_pass http://127.0.0.1:8080/api/;
        proxy_pass_request_headers on;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Content-Type $http_content_type;
    }

    # PROXY AL FRONTEND DOCKER
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Fowarded-Port $server_port;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # CLAVE: permite usar páginas de error personalizadas
        proxy_intercept_errors on;
    }

    # PROXY AL GRAFANA
    location = /grafana {
        return 301 /grafana/;
    }

    location /grafana/ {
        proxy_pass http://127.0.0.1:3001/grafana/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_redirect off;
    }

    # ERRORES PERSONALIZADOS
    error_page 404 /404.html;
    error_page 500 /500.html;
    error_page 502 /502.html;
    error_page 503 /503.html;
    error_page 504 /504.html;

    location = /404.html { internal; alias /var/www/errors/404.html; }
    location = /500.html { internal; alias /var/www/errors/500.html; }
    location = /502.html { internal; alias /var/www/errors/502.html; }
    location = /503.html { internal; alias /var/www/errors/503.html; }
    location = /504.html { internal; alias /var/www/errors/504.html; }
    location /assets/ { alias /var/www/errors/assets/; access_log off; expires 7d; }

    # managed by Certbot
    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;

    ssl_certificate /etc/letsencrypt/live/travelandrepeat.com.mx/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/travelandrepeat.com.mx/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    listen 80;
    listen [::]:80;
    server_name travelandrepeat.com.mx www.travelandrepeat.com.mx;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name www.travelandrepeat.com.mx;
    return 301 https://travelandrepeat.com.mx$request_uri;
}