name: CI/CD Docker Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  login-build-push-pull-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Generate version tags
      - name: Generate version tags
        id: vars
        run: |
          DATE_TAG=$(date +'%Y.%m.%d')
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

      # Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }} # Assuming Docker Hub username is the same as GitHub owner
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Docker Hub token stored in GitHub Secrets, 90 days expiry

      # Build & Push Image Docker Hub
      - name: Build & Push Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ github.repository_owner }}/travelandrepeatdev:latest
            ${{ github.repository_owner }}/travelandrepeatdev:${{ env.DATE_TAG }}
            ${{ github.repository_owner }}/travelandrepeatdev:${{ env.SHORT_SHA }}

      # Deploy to VPS via SSH
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "== Pulling latest image =="
            docker pull ${{ github.repository_owner }}/travelandrepeatdev:latest

            echo "== Stopping old container =="
            docker stop tyr-fe || true

            echo "== Removing old container =="
            docker rm tyr-fe || true

            echo "== Starting new container =="
            docker run -d \
              --name tyr-fe \
              --hostname tyr-fe \
              -p 80:3000 \
              ${{ github.repository_owner }}/travelandrepeatdev:latest

            echo "== Deployment completed successfully =="