name: CI/CD GHCR Deploy to VPS and send to Docker Hub

on:
  push:
    branches:
      - 'release/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Generate version tags
      - name: Generate version tags
        id: vars
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # Login to GHCR Github Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }} # assuming same username as GHCR
          password: ${{ secrets.DOCKERHUB_USERNAME_FORGITHUB }}

      # Build and push Docker image to GHCR
      - name: Build & Push Image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/travelandrepeat-fe:latest
            ghcr.io/${{ github.repository_owner }}/travelandrepeat-fe:${{ env.SHORT_SHA }}
            ${{ github.repository_owner }}/travelandrepeat-fe:latest

      # Deploy to VPS
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # Always pulled image from GHCR to keep it private
          script: |
            set -e

            IMAGE=ghcr.io/${{ github.repository_owner }}/travelandrepeat-fe:${{ env.SHORT_SHA }}

            echo "== Logging into GHCR =="
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            echo "== Pulling latest image =="
            docker pull $IMAGE

            echo "== Stopping old container =="
            docker stop tyr-fe || true

            echo "== Removing old container =="
            docker rm tyr-fe || true

            echo "== Starting new container =="
            docker run -d \
              --name tyr-fe \
              --restart unless-stopped \
              -p 3000:3000 \
              -e NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }} \
              -e NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }} \
              -e AWS_BUCKET_ACCESS_KEY_ID=${{ secrets.AWS_BUCKET_ACCESS_KEY_ID }} \
              -e AWS_BUCKET_SECRET_ACCESS_KEY=${{ secrets.AWS_BUCKET_SECRET_ACCESS_KEY }} \
              -e AWS_BUCKET_ENDPOINT=${{ secrets.AWS_BUCKET_ENDPOINT }} \
              -e AWS_BUCKET_REGION=${{ secrets.AWS_BUCKET_REGION }} \
              $IMAGE

            echo "== Deployment completed successfully =="